services:
  postgres:
    image: postgres:17
    container_name: my_postgres_db  # 给容器起一个固定的名字，方便管理
    restart: always                # 容器退出时总是自动重启
    environment:
      POSTGRES_USER: inforecon        # 设置数据库用户名
      POSTGRES_PASSWORD: inforecon  # 设置数据库密码
      POSTGRES_DB: inforecon       # ✨ 这里设置你需要的数据库名
    ports:
      - "5432:5432"                # 将容器的5432端口映射到主机的5432端口
    volumes:
      - postgres_data:/var/lib/postgresql/data # 数据持久化

volumes:
  postgres_data: 