services:
  redis-cache:
    image: redis:latest
    container_name: my-redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - my-redis-data:/data
    command: redis-server --requirepass "your-super-secret-password" --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  my-redis-data:
    driver: local